spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mz?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: mySecretKey
  expiration: 259200000

# swagger config
swagger:
  base-package: com.mz_test.domain
  path: /api/**
  title: 메가존디지털 과제 API 문서
  description: 과제 API 문서
  version: 1.0

# swagger-ui 활성화 유무
springfox:
  documentation:
    swagger-ui:
      enabled: on